## 데이터노드, 인제스트 노드, 마스터 노드(statefulset 컨트롤러 오브젝트로 생성하기) / PVC 오브젝트를 생성해 스토리지에 저장 후 DB나 S3로 보내기
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-masternode
          image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: 4G
            requests:
              cpu: 500m
              memory: 2G
          env:
            - name: discovery.type
              value: single-node

            - name: ES_JAVA_OPTS
              value: -Xms1G -Xmx1G     
              # valueFrom:
              #   configMapKeyRef:
              #     name: es-configmap
              #     key: ES_JAVA_OPTS
          ports:
            - name: http-rest
              containerPort: 9200
              protocol: TCP
            - name: tcp
              containerPort: 9300
              protocol: TCP
          # volumeMounts:
          #   - name: es-data-volume
          #     mountPath: /usr/share/elasticserach/data
      restartPolicy: Always