apiVersion: v1
kind: Service
metadata:
  name: es-service
  namespace: elk-namespace
spec:
  ports:
    - name: http-rest
      protocol: TCP
      port: 9200
      targetPort: 9200

    - name: tcp
      protocol: TCP
      port: 9300
      targetPort: 9300
