apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: kube-logging
data:
  # logstash conf
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

# logstash pipeline
  logstash.conf: |
    input {
      tcp {
        port => 5000
      }
    }

    filter {
      mutate {
      }
    }

    output {
      stdout {
        codec => rubydebug
      }


      elasticsearch {
          hosts => "http://elasticsearch-client.kube-logging.svc.cluster.local:9200"
    
      }
    }

