apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-namespace
spec:
  replicas: 1 # for test
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash

    sepc: ## volume
    